"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ===========================
# Load Environment Variables
# ===========================
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ===========================
# SECURITY SETTINGS
# ===========================
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# ✅ DEBUG should be False in production
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ✅ Allowed domains
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "electricity-board-q9zx.onrender.com",  # ✅ your actual Render backend URL from logs
    "electricity-frontend.netlify.app"      # ✅ your frontend (if you have one)
]

CSRF_TRUSTED_ORIGINS = [
    'https://electricity-board-q9zx.onrender.com',
    'http://localhost:3000/'
]


# ===========================
# INSTALLED APPS
# ===========================
INSTALLED_APPS = [
    "corsheaders",  # ✅ FIXED: Added comma here
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",  # Your custom Django app
]

# ===========================
# MIDDLEWARE
# ===========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ===========================
# URL & WSGI
# ===========================
ROOT_URLCONF = 'project.urls'
WSGI_APPLICATION = 'project.wsgi.application'

# ===========================
# TEMPLATES
# ===========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # ✅ Only needed if Django serves React build directly
        'DIRS': [BASE_DIR / "build"],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ===========================
# DATABASE
# ===========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ===========================
# PASSWORD VALIDATION
# ===========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===========================
# INTERNATIONALIZATION
# ===========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ===========================
# STATIC FILES
# ===========================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'staticfiles'  # Where collectstatic stores files

# Whitenoise compression
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# If React's build folder needs to be included in Django static files
# STATICFILES_DIRS = [BASE_DIR / "build" / "static"]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================
# CORS SETTINGS
# ===========================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",                   # React local dev
    "https://electricity-frontend.netlify.app" # ✅ your deployed frontend
]
# For debugging only, if CORS issues persist:
CORS_ALLOW_CREDENTIALS = True
DEBUG = True